#!/usr/bin/env ruby
#
# pwcrack-framework
# Author L
#

Version = '1.0.3'
Project = 'pwcrack-framework'

trap("INT"){ abort "\r[!!!] Interrupt. " }

# load lib
require_relative 'lib/str_ext'
require_relative 'lib/cli'
require_relative 'lib/core'

# load all plugins
ROOT = File.dirname(File.realpath(__FILE__))

Dir["#{ROOT}/plugins/*.rb"].each do |plugin|
  require_relative plugin
end

# commandline 
passwd, opts = CLI.commandline!

# start
PWCrack.set(opts)
PWCrack.crack(passwd)
