#!/usr/bin/env ruby
#
# pwcrack-framework
# Author L
#

Version = '1.8.7'
Project = 'pwcrack-framework'

require 'rainbow/refinement'
using Rainbow

autoload :MessagePack, 'msgpack'
autoload :Base64,      'base64'
autoload :OpenSSL,     'openssl'
autoload :Readline,    'readline'
autoload :JSON,        'json'
autoload :ProgressBar, 'ruby-progressbar'

trap("INT"){ puts "\r[!!!] Interrupt. ".red; exit! 1 }

ROOT = File.dirname(File.realpath(__FILE__))

# load all external
#Dir["#{ROOT}/external/**/*.rb"].each do |external|
#  require_relative external
#end

# load lib
require_relative 'lib/str_ext'
require_relative 'lib/cli'
require_relative 'lib/core'

# load all plugins
Dir["#{ROOT}/plugins/*.rb"].each do |plugin|
  require_relative plugin
end

# commandline 
passwd, opts = CLI.commandline!

# start
PWCrack.set(opts)
PWCrack.crack(passwd)
